external-user:
  username: admin
  password: admin


#mail-service
q.mail-queue: q.mail-queue
#notification-service
queue.notification: q.notification-queue


#DB_CONFIG
ACCESS-MANAGEMENT:
  db:
    url: jdbc:postgresql://localhost:5432/company-management
    user: postgres
    password: root
COMPANY-MANAGEMENT:
  db:
    url: jdbc:postgresql://localhost:5432/company-management
    user: postgres
    password: root

#APP_CONFIG
app_config:
  ACCESS-MANAGEMENT:
    url: http://localhost:4200
  REPORT-SERVICE:
    url: http://localhost:4200
